name: 'archlinux'

on:
  push:
    paths:
      - '.github/workflows/archlinux.yml'
      - 'archlinux/run.sh'
      - 'archlinux/community/*'
      - 'archlinux/mcode/*'
      - 'archlinux/llvm/*'
      - 'archlinux/gcc/*'
  pull_request:
  schedule:
    - cron: '0 0 * * 2,5'
  workflow_dispatch:

env:
  CI: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        pkg: [
          'community',
          'mcode',
          'llvm',
          'gcc'
        ]
    steps:

    - uses: actions/checkout@v2

    - run: TARGET=${{ matrix.pkg }} ./archlinux/run.sh

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.pkg }}
        path: archlinux/${{ matrix.pkg }}/artifacts/*
